title: RubyConf Taiwan x COSCUP 2025
description: Conference for Open Source Coders, Users & Promoters
email: info@rubyconf.tw
baseurl: ""
url: ""

plugins:
  - jekyll-tailwindcss

tailwindcss:
  css_path: "./_tailwind.css"
  config: "./tailwind.config.js"  # 添加此行指定 tailwind.config.js 位置
  
mail:
  contact: "contact@rubyconf.tw"

links:
  cfp: https://pretalx.coscup.org/coscup-2025/cfp
  cfs: https://coscup.org/2025/en/sponsorship/
  cfv: https://volunteer.coscup.org/
conf:
  root_url: 'https://rubyconf.tw'
  about_us: 'https://ruby.tw'